### ISSUE TITLE
【産総研】【対応対象外】リソース処理の指摘（init.cpp）(1)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#11]
### 今回対象外としたKlocwork上で表示されるエラー指摘
1. /home/devel/project/ws_ros/src/ros_comm/roscpp/src/libros/init.cpp
- 行 264 で   'new(sizeof(CallbackQueue))->mutex_.m' に割り当てられたリソースが失われる可能性があります。
- 行 264 で   'new(sizeof(CallbackQueue))->condition_.internal_mutex'   に割り当てられたリソースが失われる可能性があります。
- 行 264 で   'new(sizeof(CallbackQueue))->condition_.cond' に割り当てられたリソースが失われる可能性があります。
- 行 264 で   'new(sizeof(CallbackQueue))->id_info_mutex_.m' に割り当てられたリソースが失われる可能性があります。

### 以下、詳細

- 指摘カテゴリ：リソース処理の指摘
- チェッカー名：RH.LEAK
- 指摘重要度：エラー
-  対象ソース：roscpp/src/libros/init.cpp

```
    260 CallbackQueuePtr getInternalCallbackQueue()
    261 {
    262   if (!g_internal_callback_queue)
    263   {
    264     g_internal_callback_queue.reset(new CallbackQueue);
    265   }
    266
    267   return g_internal_callback_queue;
    268 }
```
264行目でnewしているCallbackQueueのリソース開放漏れの可能性を指摘している。
CallbackQueueのリソースは、g_internal_callback_queueに設定している。
ここで、g_internal_callback_queueは、
```
     97 static CallbackQueuePtr g_internal_callback_queue;
```
97行目で、グローバル変数として定義されており、
clients/roscpp/include/ros/callback_queue.hの中で、
```
typedef boost::shared_ptr<CallbackQueue> CallbackQueuePtr;
```
スマートポインタとして定義されている。boost::shared_ptrのresetで設定した場合、
設定前のポインタは、resetされた時点で破棄されるためリソースのリークにはならない。
最後に設定されたポインタは、プログラム終了時にグローバル変数から解放される。

よって、本指摘は対応不要と考える。

**Comment by sec-matsunaga** [comment]
【修正しない理由】
Klocworkはリソースの廃棄がされていない可能性を指摘しているが、実際には正しく廃棄しているため修正する意味がない。Klocworkの過剰な指摘であるため修正しない。

**Comment by r-kurose** [comment]
Klocwork が問題であったかの確認は取れていない。
確認するべきだが、分析上では問題無いということで終了する。
