### ISSUE TITLE
【産総研】【対応対象外】リソース処理の指摘（init.cpp）(2)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#12]
### 今回対象外としたKlocwork上で表示されるエラー指摘
1. /home/devel/project/ws_ros/src/ros_comm/roscpp/src/libros/init.cpp
- 行 445 で   'new(sizeof(CallbackQueue))->mutex_.m' に割り当てられたリソースが失われる可能性があります。
- 行 445 で   'new(sizeof(CallbackQueue))->condition_.internal_mutex'   に割り当てられたリソースが失われる可能性があります。
- 行 445 で   'new(sizeof(CallbackQueue))->condition_.cond' に割り当てられたリソースが失われる可能性があります。
- 行 445 で   'new(sizeof(CallbackQueue))->id_info_mutex_.m' に割り当てられたリソースが失われる可能性があります。

### 以下、詳細

- 指摘カテゴリ：リソース処理の指摘
- チェッカー名：RH.LEAK
- 指摘重要度：エラー
-  対象ソース：roscpp/src/libros/init.cpp

```
    443   if (!g_global_queue)
    444   {
    445     g_global_queue.reset(new CallbackQueue);
    446   }
```
 #11 の指摘と同様に、 g_global_queueに設定したnew CallbackQueueのポインタの解放漏れの
可能性を指摘している。
```
     95 CallbackQueuePtr g_global_queue;
```
g_global_queueは、#11 と同様のスマートポインタを利用していることから、
#11 と同様の理由により、本件も対応不要と考える。

**Comment by sec-matsunaga** [comment]
【修正しない理由】
Klocworkはリソースの廃棄がされていない可能性を指摘しているが、実際には正しく廃棄しているため修正する意味がない。Klocworkの過剰な指摘であるため修正しない。

**Comment by r-kurose** [comment]
Klocwork が問題であったかの確認は取れていない。
確認するべきだが、分析上では問題無いということで終了する。
