### ISSUE TITLE
【産総研】【対応対象外】リソース処理の指摘(internal_timer_manager.cpp)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#13]
### 今回対象外としたKlocwork上で表示されるエラー指摘
1. /home/devel/project/ws_ros/src/ros_comm/roscpp/src/libros/internal_timer_manager.cpp
- 行 58 で   'new(sizeof(TimerManager<ros::SteadyTime ros::WallDuration   ros::SteadyTimerEvent>))->timers_mutex_.m' に割り当てられたリソースが失われる可能性があります。
- 行 58 で   'new(sizeof(TimerManager<ros::SteadyTime ros::WallDuration   ros::SteadyTimerEvent>))->timers_cond_.internal_mutex'   に割り当てられたリソースが失われる可能性があります。
- 行 58 で   'new(sizeof(TimerManager<ros::SteadyTime ros::WallDuration   ros::SteadyTimerEvent>))->timers_cond_.cond' に割り当てられたリソースが失われる可能性があります。
- 行 58 で   'new(sizeof(TimerManager<ros::SteadyTime ros::WallDuration   ros::SteadyTimerEvent>))->waiting_mutex_.m' に割り当てられたリソースが失われる可能性があります。
- 行 58 で   'new(sizeof(TimerManager<ros::SteadyTime ros::WallDuration   ros::SteadyTimerEvent>))->id_mutex_.m' に割り当てられたリソースが失われる可能性があります。

### 以下、詳細
- 指摘カテゴリ：リソース処理の指摘
- チェッカー名：RH.LEAK
- 指摘重要度：エラー
-  対象ソース：roscpp/src/libros/internal_timer_manager.cpp

```
     54 void initInternalTimerManager()
     55 {
     56   if (!g_timer_manager)
     57   {
     58     g_timer_manager.reset(new InternalTimerManager);
     59   }
     60 }
```
本件も、 #11 と同様に、58行目でnewしているInternalTimerManagerの解放漏れの可能性に対する
指摘である。

```
     47 static InternalTimerManagerPtr g_timer_manager;
```
47行目で指定しているスマートポインタInternalTimerManagerPtrは、
internal_timer_manager.h
```
     40 typedef boost::shared_ptr<InternalTimerManager> InternalTimerManagerPtr;
```
となっており、 #11 と同様の理由により、本件も対応不要と考える。

**Comment by sec-matsunaga** [comment]
【修正しない理由】
Klocworkはリソースの廃棄がされていない可能性を指摘しているが、実際には正しく廃棄しているため修正する意味がない。Klocworkの過剰な指摘であるため修正しない。

**Comment by r-kurose** [comment]
Klocwork が問題であったかの確認は取れていない。
確認するべきだが、分析上では問題無いということで終了する。
