### ISSUE TITLE
【産総研】【要対応】到達不能コード(rosout_appender.cpp)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#15]
- 指摘カテゴリ：到達不能コード
- チェッカー名：INFINITE_LOOP.GLOBAL
- 指摘重要度：エラー
-  対象ソース：roscpp/src/libros/rosout_appender.cpp

```
    117 void ROSOutAppender::logThread()
    118 {
    119   while (!shutting_down_)
    120   {
    121     V_Log local_queue;
    122
    123     {
    124       boost::mutex::scoped_lock lock(queue_mutex_);
```

上記の119行目のwhile文が完了しないことにより、while文の外に処理が進まない可能性を指摘している。

```
     58 ROSOutAppender::~ROSOutAppender()
     59 {
     60   shutting_down_ = true;
     61
     62   {
     63     boost::mutex::scoped_lock lock(queue_mutex_);
     64     queue_condition_.notify_all();
     65   }
     66
     67   publish_thread_.join();
     68 }
```
shutting_down_ はメンバ変数であり、デストラクタの60行目で真に変更されている。
よって、デストラクタ呼び出しタイミングで、上記のwhileループは処理を抜ける。
67行目のpublish_thread_.join();にて、whileループの終了と合流し、処理を終了する。
ここで、publish_thread_は、同ファイルの49行目で、

```
     47 ROSOutAppender::ROSOutAppender()
     48 : shutting_down_(false)
     49 , publish_thread_(boost::bind(&ROSOutAppender::logThread, this))
     50 {
```
117行目のlogThreadが設定されている。
よって、デストラクタ呼び出しタイミングで、先ほどのwhileループは完了し、処理を抜けるため、
後続の処理も到達可能であり、本指摘は対応する必要がないと考える。

**Comment by sec-matsunaga** [comment]
~~【修正しない理由】
Klocworkは、whileループの条件がループ内で変更されないことを根拠に無限ループの可能性を指摘していると思われる。実際には、上記に示すようにデストラクタの処理内でループを抜ける実装になっており、指摘が正しくない。よって修正しない。~~

whileループの条件に使用している変数に対して、volatileの設定を行い、最適化をかけないことを明示することで本指摘が消えることを確認した。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
