### ISSUE TITLE
【産総研】【要対応】バッファ境界をチェックしない関数'strcpy'を使用している。

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#2]
- 指摘カテゴリ：バッファオーバーフロー 
- チェッカー名：SV.STRBO.UNBOUND_COPY
- 指摘重要度：重大

IPアドレスを固定サイズのバッファにコピーする際に、strcpyを使用している。
strcpyはバッファ境界をチェックしないため、バッファオーバフローする可能性がある。

inet_ntop関数を利用して、IPアドレスをコピーするように修正する。
参考：https://linuxjm.osdn.jp/html/LDP_man-pages/man3/inet_ntop.3.html

**Comment by sec-matsunaga** [comment]
最新のmelodicのコードだと該当部分は、「strncpy」に変更されている。IPアドレスのコピーなので、inet_ntopの方がより良いように思える。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
