### ISSUE TITLE
travisの設定ファイルを追加する。

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#25]

**Comment by r-kurose** [comment]
設定ファイルを取り込みましたがワーニングがあるようです。
https://travis-ci.org/robo-marc/ros_comm/jobs/627526780/config?utm_medium=notification&utm_source=github_status

**Comment by r-kurose** [comment]
https://travis-ci.org/robo-marc/ros_comm/jobs/627526780?utm_medium=notification&utm_source=github_status
テストでFAILしているのですが、リターンコードが0なのでTravis CIの最終結果がOKになっています。

**Comment by sec-matsunaga** [comment]
はい、テストFailの件、承知しております。原因調査中です。
ちなみに、ワーニングの方が見つけられなかったのですが、どの部分かご教示いただけますでしょうか。

**Comment by sec-matsunaga** [comment]
警告の内容について調査したところ
sudo: required
の表現がtravisのバージョンアップに伴い、不要になったとのこと。
上記を.travis.ymlから除いたところ警告が出なくなった。
参考 [https://qiita.com/Sekky0905/items/c8ab425734304d9c30ea](url)

**Comment by r-kurose** [comment]
警告がなくなったことを確認しました。
