### ISSUE TITLE
travisでのcatkin_make run_testsでのエラー

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#27]
travisでのcatkin_make run_testsを実施した際に、テストでFailが発生する。
最終値が0で返っているため、travisの結果としてはOKに見えるが、テスト自体は一部の項目でRESULT: FAILがある。

check_roswtf_command_line_online.py
random_play.py
にて発生している。

random_play.pyのエラーについては、成功するケース（同じ試験でもランダムに成功、失敗になる）もある。

**Comment by sec-matsunaga** [comment]
kinetic-develの最新（commit a4cd1fa4 ) でも同様の事象が発生することを確認している。

**Comment by r-kurose** [comment]
本対応と関係なく発生する問題のために、ここでは対応しない。
