### ISSUE TITLE
【産総研】【要対応】NULL参照する可能性のあるコード

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#3]
- 指摘カテゴリ：NULLポインタの逆参照
- チェッカー名：NPD.FUNC.MUST,NPD.CHECK.MUST,NPD.FUNC.MIGHT
- 指摘重要度：重大

NULLポインタが返却される可能性のある関数の戻り値をNULLチェックせずに処理している。

ROS_ASSERT_ENABLEDが未定義の場合、静的解析で指摘されているコードを通過する可能性がある。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
