### ISSUE TITLE
 【産総研】【要対応】初期化をしていない変数の利用（xmlrpcpp）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#4]
- 指摘カテゴリ：未初期化のデータの使用 
- チェッカー名：UNINIT.CTOR.MUST
- 指摘重要度：エラー

コンストラクタで初期化しておくべきデータの初期化を行う。
xmlrpcppのソースコードを対象とする。

**Comment by sec-matsunaga** [comment]
melodic版では該当箇所の初期化処理は追加されている。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
