### ISSUE TITLE
【産総研】【要対応】NULL参照する可能性のあるコード(ロガーマクロ)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#5]
- 指摘カテゴリ：NULLポインタの逆参照
- チェッカー名：NPD.GEN.CALL.MIGHT
- 指摘重要度：重大

`void initializeLogLocation(LogLocation* loc, const std::string& name, Level level)
{
  loc->logger_ = ::ros::console::impl::getHandle(name);`

Loggerの初期化時に、loc->logger_にNULLが設定された場合、

`    ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)`
の第二引数にNULLが格納され、printの内部で、NULL参照する可能性がある。

**Comment by sec-matsunaga** [comment]
melodic版では、今回修正対象のconsole.hというファイル自体がなくなっている。（大本のrosconsole
ディレクトリ自体がない。)別の何かに統合されている可能性はある。

**Comment by sec-matsunaga** [comment]
rosconsole_print.cpp
処理の中では、__rosconsole_define_location__loc.logger_にゼロを設定しているため、単純にprintの前でNULLチェックをするのは適切ではない。（rosconsole_print.cppでは、print内で、logger_を利用していないので、0で問題ない）

**Comment by sec-matsunaga** [comment]
rosconsole_log4cxx.cpp
のみがhandlerをポインタとして利用しているため、そのprint処理の中で、NULLチェックを行う。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
