### ISSUE TITLE
【産総研】【要対応】初期化をしていない変数の利用（roscpp/src）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/ros_comm#7]
- 指摘カテゴリ：未初期化のデータの使用 
- チェッカー名：UNINIT.STACK.MUST、UNINIT.CTOR.MUST
- 指摘重要度：重大、エラー

io.cpp
```
    325                         socket_pollfd pfd;
```
の変数が一部（events）が未初期化である。
※eventsの値は、/usr/include/x86_64-linux-gnu/bits/poll.hに定義しているPOLLIN（0ｘ001）等の
ビットフラグ値が設定されるため未指定を0x0000として初期化する。

service_client.hの中で定義している以下のメンバ変数が未初期化である。
```
    198     bool persistent_;
```

statistics.hの中で定義している以下のメンバ変数が未初期化である。初期値としてはそれぞれの
デフォルト値を採用する。
```
     70   // these are hard constrains
     71   int max_window;
     72   int min_window;
     73
     74   // these are soft constrains
     75   int max_elements;
     76   int min_elements;
     77
     78   bool enable_statistics;
```
steady_timer.h、timer.h、wall_timer.hで以下の変数が未初期化である。
```
    112     CallbackQueueInterface *callback_queue_;
    114     bool has_tracked_object_;
    115     bool oneshot_;
```

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
